spring.application.name=EndTerm-Project
spring.datasource.url=jdbc:postgresql://localhost:5432/freelanceDB
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jackson.deserialization.fail-on-null-for-primitives=false